######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 18 22:13:45 2020
######################################################################

QT += opengl
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += globj.h
SOURCES += globj.cpp main.cpp

